### PR TITLE
Replace `exa` with `eza`

### PR DESCRIPTION
**Pull request by nuke-web3**
https://github.com/ogham/exa#exa-is-unmaintained-use-the-fork-eza-instead

### CODE REVIEW

**Review by port19x — APPROVED** [review]

**Review by murdos — APPROVED** [review]

**Comment by isbm** [comment]
Damn. Thanks to this page I've package `exa` instead of `eza` and now I need to repackage everything. 😭

**Review by jisungbin — APPROVED** [review]

**Comment by NukeManDan** [comment]
@ibraheemdev  :pray: might you approve?

**Comment by johnalanwoods** [comment]
is this repo still maintained

**Comment by bermudi** [comment]
> is this repo still maintained

short answer is no

**Comment by johnalanwoods** [comment]
Done at: https://github.com/johnalanwoods/maintained-modern-unix

**Comment by ibraheemdev** [comment]
Getting around to merging some PRs... thanks!

**Pull request merged**
