### PR TITLE
Add VisiData a modern TUI for exploring data.

### PR DESCRIPTION
**Pull request by frosencrantz**

### CODE REVIEW

**Comment by frosencrantz** [comment]
VisiData is a wonderful terminal tool for exploring data.  It seems like most of the tools on this list are written in Rust, VisiData is written in Python and is very responsive.  There is no equivalent in Rust/C/Go/etc and it fills a niche that is not covered well by any other terminal tool.  I've been using this tool for several years now, and still it is one my favorite finds over the last couple years, even over many of the other tools in this list.

**Comment by MrMino** [comment]
@frosencrantz which common Unix command is this the alternative to?

**Comment by MrMino** [comment]
@frosencrantz which common Unix command is it an alternative to?

**Comment by frosencrantz** [comment]
I don't think it has a direct replacement.  But I've found I use awk/sed/cut/sort a lot less since I started using VisiData.
 So it ends up being a great replacement for awk/sed/cut/sort for how I generally use those tools, which is to gather some details about some data file or output of some Unix system command that generate tabular data like ps.

**Comment by MrMino** [comment]
For convenience: https://github.com/saulpw/visidata

**Comment by blaggacao** [comment]
If it doesn't work with `nix` out of the box, that's at least a bit suspicious upfront.

```
$ nix profile install nixpkgs#visidata

$ vd --version
Traceback (most recent call last):
  File "/nix/store/slqf9074ha8km0xf3x5vykz4nc7vcqab-visidata-2.5/bin/.vd-wrapped", line 7, in <module>
    visidata.main.vd_cli()
  File "/nix/store/slqf9074ha8km0xf3x5vykz4nc7vcqab-visidata-2.5/lib/python3.9/site-packages/visidata/main.py", line 320, in vd_cli
    rc = main_vd()
  File "/nix/store/slqf9074ha8km0xf3x5vykz4nc7vcqab-visidata-2.5/lib/python3.9/site-packages/visidata/main.py", line 84, in main_vd
    locale.setlocale(locale.LC_ALL, '')
  File "/nix/store/81lwy2hfqj4c1943b1x8a0qsivjhdhw9-python3-3.9.6/lib/python3.9/locale.py", line 610, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

**Comment by frosencrantz** [comment]
I'm not familiar with `nix`.  Some simple searches suggested:  https://nixos.wiki/wiki/Locales 
@blaggacao does that help?   You can report a bug here https://github.com/saulpw/visidata/issues

**Comment by ibraheemdev** [comment]
Not really the type of tool I am looking for. I realize there are not really clear contribution guidelines at this point, sorry!

**Pull request closed without merging**
