### PR TITLE
Add shell-uglify

### PR DESCRIPTION
**Pull request by gytis-ivaskevicius**
Add shell-uglify

### CODE REVIEW

**Comment by slavaGanzin** [comment]
https://github.com/hoodie/shell-uglify/blob/master/uglify.sh

Is this a joke?

**Comment by MagicRB** [comment]
This tool is awesome! It really bring out the ugly in all my shell scripts!

**Comment by giopaglia** [comment]
LOL

**Comment by MatthewCroughan** [comment]
> https://github.com/hoodie/shell-uglify/blob/master/uglify.sh
> 
> Is this a joke?

No. Where's the funny?

**Comment by cuahangtemplate** [comment]
haha

**Comment by isbm** [comment]
@gytis-ivaskevicius this is stupid. 😞

**Pull request closed without merging**
