### PR TITLE
feat: refactor modern *nix tools presentation

### PR DESCRIPTION
**Pull request by yozachar**
I'm happy to spare available time to maintain this repository @ibraheemdev

----

**Related Items**

*Issues*:

- Closes: #27

### CODE REVIEW

**Comment by joe733** [comment]
Preview @ https://github.com/joe733/modern-unix/tree/workshop

image

**Comment by jankatins** [comment]
Perosnally, I would find it easier to "scan" if the shields were in a separate column (or at least line) than the name. Right now, the name is easily overlooked because it's usually very short and looks a bit like a shield could not be loaded :-(

Maybe add it as a separate paragraph/line under the description: that line is already long and so the long line of shields do not visually "overshadow" the description like it does for the name?

**Comment by joe733** [comment]
Updated preview @ https://github.com/joe733/modern-unix/tree/workshop

image

<details><summary><code>Source</code></summary>

```md
# Modern Unix

| Name                     | Description                                                            | Status                                                         | Screenshot                                       |
| ------------------------ | ---------------------------------------------------------------------- | -------------------------------------------------------------- | ------------------------------------------------ |
| [`ag`][ag]               | A code searching tool similar to `ack`, but faster.                    | ![_][ag-ghst] ![_][ag-lang] ![_][ag-ghlc]                      | <img width="300" src="./assets/ag.png" />        |
| [`bat`][bat]             | A `cat` clone with syntax highlighting and Git integration.            | ![_][bat-ghst] ![_][bat-lang] ![_][bat-ghlc]                   | <img width="300" src="./assets/bat.png" />       |

...

<!--Links-->

<!--ag -->

[ag]: https://github.com/ggreer/the_silver_searcher
[ag-ghlc]: https://img.shields.io/github/last-commit/ggreer/the_silver_searcher?label=%F0%9F%92%BB
[ag-ghst]: https://img.shields.io/github/stars/ggreer/the_silver_searcher?label=%E2%AD%90
[ag-lang]: https://img.shields.io/github/languages/top/ggreer/the_silver_searcher

<!--bat-->

[bat]: https://github.com/sharkdp/bat
[bat-ghlc]: https://img.shields.io/github/last-commit/sharkdp/bat?label=%F0%9F%92%BB
[bat-ghst]: https://img.shields.io/github/stars/sharkdp/bat?label=%E2%AD%90
[bat-lang]: https://img.shields.io/github/languages/top/sharkdp/bat

...
```

</details>

**Comment by mgrzaslewicz** [comment]
It would be great to merge it. It's a good improvement

**Comment by johnalanwoods** [comment]
love this, please PR to my maintained fork here: https://github.com/johnalanwoods/maintained-modern-unix

**Comment by johnalanwoods** [comment]
@yozachar - I can add collaborators without using an org, want to be added?

**Pull request closed without merging**
