### PR TITLE
Added Brewfile

### PR DESCRIPTION
**Pull request by upgundecha**
Added Brewfile as proposed in https://github.com/ibraheemdev/modern-unix/issues/57
macOS users can install tools listed in this repository using Homebrew and Brewfile

### CODE REVIEW

**Comment by SirCipherz** [comment]
that doesn't look very useful, why wouldn't people want every single program listed there ? it's not a long operation to just type "brew program"

**Comment by slavaGanzin** [comment]
@SirCipherz If you don't think it's useful, it doesn't mean it is. I think this is useless too, but @upgundecha spent his time making PR while thinking it is, so why should we judge?

**Comment by upgundecha** [comment]
Hey guys no worries 😀 I respect your feedback. TBH it was useful for me to get these awesome tools installed using a single Brewfile. I can withdraw this PR and instead use the Gist that I originally created.

**Comment by SirCipherz** [comment]
> @SirCipherz If you don't think it's useful, it doesn't mean it is. I think this is useless too, but @upgundecha spent his time making PR while thinking it is, so why should we judge?

i could spend a long time making a pull request for the windows calculator in order to add torrents support, it's not because i spent time on it that it should be merged. if the purpose of the patch is kind of useless there is no reason to merge it

**Pull request closed without merging**
